import { dateKey, addDays, toISO } from "./domain.js";
export function createDemo() {
  const today = dateKey();
  const at = (days, time) => toISO(`${addDays(today, days)}T${time}`);
  const teams = ["Team A", "Team B", "Team C", "Helper", "Unassigned"].map(
    (name, i) => ({ id: `team-${i}`, name, is_active: true }),
  );
  const specs = [
    [
      "BMW 320i",
      "Alpine White",
      "Full PPF",
      1,
      "In Progress",
      0,
      "17:00",
      ["Done", "Done", "Ongoing", "Pending", "Pending"],
      "Prioritize the front bumper. Customer pickup at 5 PM.",
    ],
    [
      "Toyota Land Cruiser",
      "Attitude Black",
      "SPF99 + Tint",
      0,
      "In Progress",
      1,
      "16:00",
      ["Done", "Done", "Ongoing", "Pending"],
      "",
    ],
    [
      "Porsche 911",
      "GT Silver",
      "Ceramic Coating",
      2,
      "Ready for Release",
      0,
      "18:00",
      ["Done", "Done", "Done", "Done"],
      "Final inspection completed. Ready for customer pickup.",
    ],
    [
      "Ford Everest",
      "Snowflake White",
      "PPF Repair",
      1,
      "In Progress",
      -1,
      "17:00",
      ["Done", "Blocked", "Pending"],
      "Waiting for replacement film for the left door.",
    ],
    [
      "Honda Civic",
      "Sonic Gray",
      "SPF89+",
      0,
      "Final Checking",
      0,
      "19:00",
      ["Done", "Done", "Done", "Ongoing"],
      "",
    ],
    [
      "Mercedes-Benz GLC",
      "Obsidian Black",
      "Full PPF",
      2,
      "In Progress",
      2,
      "17:00",
      ["Done", "Ongoing", "Pending", "Pending", "Pending"],
      "",
    ],
    [
      "Mazda CX-5",
      "Soul Red",
      "Reboost",
      3,
      "Pending",
      1,
      "15:00",
      ["Pending", "Pending", "Pending"],
      "",
    ],
    [
      "Toyota Fortuner",
      "Pearl White",
      "SPF99",
      4,
      "Ingress",
      1,
      "18:00",
      ["Pending", "Pending", "Pending"],
      "Confirm package on arrival.",
    ],
    [
      "Suzuki Jimny",
      "Jungle Green",
      "Full PPF",
      0,
      "Ingress",
      3,
      "17:00",
      ["Pending", "Pending", "Pending", "Pending"],
      "",
    ],
  ];
  const taskNames = [
    "Wash & decontamination",
    "Paint correction",
    "Film / coating application",
    "Interior & finishing",
    "Final inspection",
  ];
  const vehicles = specs.map((s, i) => ({
    id: `vehicle-${i}`,
    vehicle_name: s[0],
    color: s[1],
    package_label: s[2],
    team_id: teams[s[3]].id,
    team_name: teams[s[3]].name,
    overall_status: s[4],
    ingress_datetime: at(
      i === 7 ? 0 : i === 8 ? 1 : -2,
      i === 7 ? "14:00" : "09:00",
    ),
    expected_release_datetime: at(s[5], s[6]),
    actual_release_datetime: null,
    notes: s[8],
    is_archived: false,
    created_at: at(-2, "08:00"),
    updated_at: new Date().toISOString(),
    tasks: s[7].map((status, n) => ({
      id: `task-${i}-${n}`,
      vehicle_id: `vehicle-${i}`,
      task_name: taskNames[n],
      status,
      sort_order: n,
      notes: "",
    })),
  }));
  return { teams, vehicles, plans: [] };
}
